
CREATE TABLE IF NOT EXISTS active_signals (
  id bigint generated by default as identity primary key,
  ticker text NOT NULL,
  signal_type text NOT NULL,  -- 'CRASH', 'SIGMA_EVENT', 'HIGH_VOLATILITY'
  severity float,  -- Z-score or panic score  
  timestamp timestamptz default now(),
  metadata jsonb  -- Full Scout Agent result data
);

-- Table 2: Verified Threats (Correlated Misinformation + Stock Crashes)
CREATE TABLE IF NOT EXISTS verified_threats (
  id bigint generated by default as identity primary key,
  event_id text UNIQUE,  -- Format: TICKER_YYYYMMDD_HHMMSS
  ticker text NOT NULL,
  crash_timestamp timestamptz,
  current_price float,
  projected_loss float,  -- Percentage drop
  z_score float,
  smoking_gun_headline text,
  smoking_gun_link text,
  article_timestamp timestamptz,
  latency_minutes float,  -- Time between article and crash
  panic_score integer,  -- 0-100
  correlation_confidence integer,  -- 0-100
  responses jsonb,  -- Generated crisis responses
  response_deployed boolean default false,
  created_at timestamptz default now(),
  metadata jsonb
);

-- Table 3: Deployed Measures (Crisis Responses Activated)
CREATE TABLE IF NOT EXISTS deployed_measures (
  id bigint generated by default as identity primary key,
  event_id bigint references verified_threats(id),
  measure_type text NOT NULL,  -- 'cease_desist', 'official_denial', 'ceo_alert'
  current_stock_price float,
  stock_price_at_deployment float,
  deployed_at timestamptz default now(),
  effectiveness text,  -- 'SUCCESS', 'FAILURE', 'NEUTRAL' (measured later)
  metadata jsonb
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_active_signals_timestamp ON active_signals(timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_active_signals_ticker ON active_signals(ticker);
CREATE INDEX IF NOT EXISTS idx_verified_threats_ticker ON verified_threats(ticker);
CREATE INDEX IF NOT EXISTS idx_verified_threats_created ON verified_threats(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_deployed_measures_event ON deployed_measures(event_id);
