-- Aegis Protocol — Complete Production Database Schema (Supabase / PostgreSQL)
-- ==============================================================================

-- Enable UUID extension if not enabled
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- Table 1: Core Verified Claims
CREATE TABLE IF NOT EXISTS claims (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  claim_hash text UNIQUE NOT NULL,
  claim_text text NOT NULL,
  normalized_text text NOT NULL,
  status text NOT NULL DEFAULT 'pending', -- 'pending', 'in_progress', 'completed', 'failed'
  verdict text, -- 'True', 'False', 'Misleading', 'Partially True', 'Unverified', 'Insufficient Evidence'
  confidence float, -- 0.0 to 1.0
  severity text, -- 'Low', 'Medium', 'High', 'Critical'
  reasoning text,
  source_url text,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- Table 2: Source-Grounded Evidence Items
CREATE TABLE IF NOT EXISTS evidence (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  claim_id uuid REFERENCES claims(id) ON DELETE CASCADE,
  source_url text,
  canonical_url text,
  publisher text,
  title text,
  stance text NOT NULL DEFAULT 'supporting', -- 'supporting', 'refuting', 'neutral'
  summary text NOT NULL,
  retrieval_method text DEFAULT 'agent_reach_scraper',
  retrieval_timestamp timestamptz DEFAULT now(),
  metadata jsonb DEFAULT '{}'::jsonb
);

-- Table 3: Active Market Signals (Scout Agent Financial Surveillance)
CREATE TABLE IF NOT EXISTS active_signals (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ticker text NOT NULL,
  signal_type text NOT NULL, -- 'CRASH', 'SIGMA_EVENT', 'HIGH_VOLATILITY'
  severity float, -- Z-score or panic score
  timestamp timestamptz DEFAULT now(),
  metadata jsonb
);

-- Table 4: Verified Financial Threats (Correlated Misinformation + Stock Crashes)
CREATE TABLE IF NOT EXISTS verified_threats (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id text UNIQUE, -- Format: TICKER_YYYYMMDD_HHMMSS
  ticker text NOT NULL,
  crash_timestamp timestamptz,
  current_price float,
  projected_loss float, -- Percentage drop
  z_score float,
  smoking_gun_headline text,
  smoking_gun_link text,
  article_timestamp timestamptz,
  latency_minutes float, -- Time between article and crash
  panic_score integer, -- 0-100
  correlation_confidence integer, -- 0-100
  responses jsonb, -- Generated crisis responses
  response_deployed boolean DEFAULT false,
  created_at timestamptz DEFAULT now(),
  metadata jsonb
);

-- Table 5: Deployed Countermeasures (Crisis Responses Activated)
CREATE TABLE IF NOT EXISTS deployed_measures (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id bigint REFERENCES verified_threats(id) ON DELETE CASCADE,
  measure_type text NOT NULL, -- 'cease_desist', 'official_denial', 'ceo_alert'
  current_stock_price float,
  stock_price_at_deployment float,
  deployed_at timestamptz DEFAULT now(),
  effectiveness text, -- 'SUCCESS', 'FAILURE', 'NEUTRAL'
  metadata jsonb
);

-- Indexes for Query Optimization
CREATE INDEX IF NOT EXISTS idx_claims_hash ON claims(claim_hash);
CREATE INDEX IF NOT EXISTS idx_claims_created ON claims(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_claims_status ON claims(status);
CREATE INDEX IF NOT EXISTS idx_evidence_claim_id ON evidence(claim_id);
CREATE INDEX IF NOT EXISTS idx_active_signals_timestamp ON active_signals(timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_active_signals_ticker ON active_signals(ticker);
CREATE INDEX IF NOT EXISTS idx_verified_threats_ticker ON verified_threats(ticker);
CREATE INDEX IF NOT EXISTS idx_verified_threats_created ON verified_threats(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_deployed_measures_event ON deployed_measures(event_id);
